chore(go.mod): bump to go 1.22
Go 1.22 is the minimum supported Go version right now.
Bump the constraint in go.mod to reflect that,
and also pick up the `for` loop semantic changes made in Go 1.22 [1].

  [1]: https://go.dev/blog/loopvar-preview

Without this, `go vet` fails on the latest Go with:

```
Error: app_test.go:441:6: loopclosure: loop variable tt captured by func literal (govet)
Error: app_test.go:451:26: loopclosure: loop variable tt captured by func literal (govet)
Error: app_test.go:466:7: loopclosure: loop variable tt captured by func literal (govet)
Error: app_test.go:473:7: loopclosure: loop variable tt captured by func literal (govet)
Error: app_test.go:479:6: loopclosure: loop variable tt captured by func literal (govet)
Error: app_test.go:546:7: loopclosure: loop variable tt captured by func literal (govet)
Error: app_test.go:559:8: loopclosure: loop variable tt captured by func literal (govet)
Error: app_test.go:574:6: loopclosure: loop variable tt captured by func literal (govet)
Error: app_test.go:597:22: loopclosure: loop variable tt captured by func literal (govet)
Error: app_test.go:604:8: loopclosure: loop variable tt captured by func literal (govet)
```