Fix race in timeout error report (#754)
In the timeout tests where we intentionally make hooks timeout and check the error messages, I noticed that it sometimes fails with errors like this:

```
        writer.go:40: [Fx] ERROR		Start failed, rolling back: context deadline exceeded
        app_test.go:698: 
            	Error Trace:	app_test.go:698
            	Error:      	"context deadline exceeded" does not contain "OnStart hook added by go.uber.org/fx_test.TestAppStart.func2.3 failed: context deadline exceeded"
            	Test:       	TestAppStart/TimeoutWithFinishedHooks
        app_test.go:701: 
            	Error Trace:	app_test.go:701
            	Error:      	Expect "context deadline exceeded" to match "app_test.go:\d+"
            	Test:       	TestAppStart/TimeoutWithFinishedHooks
        app_test.go:706: 
            	Error Trace:	app_test.go:706
            	Error:      	"-1" is not greater than "-1"
            	Test:       	TestAppStart/TimeoutWithFinishedHooks
    writer.go:40: [Fx] ERROR		Start failed, rolling back: context canceled
```

There were two races:

1. It's possible for the goroutine executing the OnStart hook itself to see the timeout error first, then return it, which will hit the `err := <- c` case in `withTimeout`, which just returns the error as it is. 

Fixed this race by checking for the timeout error in the `err := <- c` case and format the error the same way as when the parent goroutine sees the timeout error first. 

2. When the timeout error is returned from the onStart to the main goroutine, the main goroutine pokes at the lifecycle's records field while the onStart-executing goroutine is trying to unroll using Stop(), which overwrites that records field. 

Fixed this race by splitting the records field into start records and stop records which are reported separately.